<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Withdrawals.aspx.cs" Inherits="Withdrawals" Culture="auto" meta:resourcekey="PageResource1" UICulture="auto" %>

<%@ Register Src="~/ucFinancials.ascx" TagPrefix="uc1" TagName="ucFinancials" %>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head id="Head1" runat="server">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <!-- Apple devices fullscreen -->
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <!-- Apple devices fullscreen -->
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <title>Withdrawals</title>
    <!-- Bootstrap -->
    <link rel="stylesheet" href="css/bootstrap.min.css" meta:resourcekey="bootstrap" runat="server" />
    <!-- Bootstrap responsive -->
    <link rel="stylesheet" href="css/bootstrap-responsive.min.css" meta:resourcekey="bootstrapresponsive" runat="server" />
    <!-- Theme CSS -->
    <link rel="stylesheet" href="css/style.css" meta:resourcekey="style" runat="server" />
    <!-- jQuery UI -->
    <link rel="stylesheet" href="css/plugins/jquery-ui/smoothness/jquery-ui.css" />
    <link rel="stylesheet" href="css/plugins/jquery-ui/smoothness/jquery.ui.theme.css" />
    <!-- Color CSS -->
    <link rel="stylesheet" href="css/themes.css" />
    <!-- GridView CSS -->
    <link rel="stylesheet" href="css/gridview.css" />
    <!-- jQuery -->
    <%--   <script type="text/javascript" src="js/jquery.min.js"></script>--%>
    <script src="Scripts/jquery-1.10.2.min.js"></script>
    <!-- My Library -->
    <script type="text/javascript" src="js/FQuery.js"></script>
    <!-- jQuery UI -->
    <script type="text/javascript" src="js/plugins/jquery-ui/jquery.ui.core.min.js"></script>
    <script type="text/javascript" src="js/plugins/jquery-ui/jquery.ui.widget.min.js"></script>
    <script type="text/javascript" src="js/plugins/jquery-ui/jquery.ui.mouse.min.js"></script>
    <script type="text/javascript" src="js/plugins/jquery-ui/jquery.ui.resizable.min.js"></script>
    <script type="text/javascript" src="js/plugins/jquery-ui/jquery.ui.sortable.min.js"></script>
    <!-- Bootstrap -->
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!-- NiceScroll -->
    <script type="text/javascript" src="js/plugins/nicescroll/jquery.nicescroll.min.js"></script>
    <!-- mNotification -->
    <link href="css/toastr.css" rel="stylesheet" />
    <script src="js/toastr.js"></script>
    <!-- ion.sound -->
    <script type="text/javascript" src="js/ion.sound.min.js"></script>
    <!-- mQuery -->
    <script src="js/mQuery.js"></script>
    <!-- persianumber -->
    <script src="js/persianumber.min.js"></script>
    <!--Reference the SignalR library. -->
    <script src="Scripts/jquery.signalR-2.0.2.min.js"></script>
    <!--Reference the autogenerated SignalR hub script. -->
    <script src="signalr/hubs"></script>
    <!-- Theme framework -->
    <script type="text/javascript" src="js/eakroko.min.js"></script>
    <!-- Theme scripts -->
    <script type="text/javascript" src="js/application.min.js"></script>
    <!-- Just for demonstration -->
    <script type="text/javascript" src="js/demonstration.min.js"></script>
    <!--[if lte IE 9]>
		<script type="text/javascript" src="js/plugins/placeholder/jquery.placeholder.min.js"></script>
		<script>
			$(document).ready(function() {
				$('input, textarea').placeholder();
			});
		</script>
		<![endif]-->
    <!-- umbrella -->
    <link rel="shortcut icon" href="img/umbrella.ico" />
    <!-- Apple devices Homescreen icon -->
    <link rel="apple-touch-icon-preClinic_udosed" href="img/apple-touch-icon-preClinic_udosed.png" />
    <script type="text/javascript">
        // Declare a proxy to reference the hub.
        var serverHub = $.connection.myHub1;
        $(function () {
            /// Eng.Moustafa Ebrahem
            /// Eng.Moustafa20@Gmail.com
            $('a[href="Withdrawals.aspx"]').parent().addClass('active');
            DoWork();
            Sys.WebForms.PageRequestManager.getInstance().add_endRequest(requestHandler);

        });
        function requestHandler(sender, args) {
            // this code is excected after the first postback
            DoWork();
        };
        function DoWork() {
            // make connection with hub
            $.connection.hub.start();
            // assign doSomething function
            serverHub.client.doSomething = function () {
                //$('#txtClinic_udAmount').val("4");
                //$('#txtClinic_udCode').val("4");
                Page_ClientValidate('');
                //$('#txtClinic_udAmount').val("");
                //$('#txtClinic_udCode').val("");
                __doPostBack('btnRefresh', '');
            }
            /////////////////////////////////////////////////
            ///////////// Clinic_ud Tab /////////////////////
            /////////////////////////////////////////////////
            $('#btnClinic_udSave').attr('disabled', true);

            $('#btnClinic_udNew').click(function () {
                ClearClinic_udtbl();
            });

            $('#btnClinic_udSave').unbind("click").bind("click", function (event) {
                event.preventDefault();
                if (!Page_ClientValidate('c')) { return false; }
                $('#modal-1').modal('show');
                $('#modal-1 #btnConfirm').unbind("click").bind("click", function () {
                    $('#btnClinic_udSave').attr('disabled', true);
                    $('#btnClinic_udNew').attr('disabled', true);
                    $('#btnClinic_udSave').attr('value', 'Saving');
                    __doPostBack('btnClinic_udSave', '');
                });
            });
            $("#gvClinic_ud .gvrow").click(function () {
                $("#gvClinic_ud .gvrow").removeClass("blue3");
                $(this).addClass("blue3");
                var cells = $(this).find("td");
                $("#txtClinic_udId").val($(cells[0]).text());
                $("#txtClinic_udCode").val($(cells[2]).text());
                $("#txtClinic_udBalance").val($(cells[3]).text());
                $('#btnClinic_udSave').attr('disabled', false);
                //Page_ClientValidate("c");
            });

            $(".gvrow2").click(function () {
                //$("#gvClinic_udTransaction .gvrow").removeClass("blue3");
                $(this).toggleClass("blue3");
            });

            $('#txtSrchDategvClinic_udTrans').keyup(function () {
                $('#txtSrchCodegvClinic_udTrans').val('');
                $("#gvClinic_udTransaction .gvrow").removeClass("blue3");
                var searchKey = $.trim($('#txtSrchDategvClinic_udTrans').val().toLowerCase());
                $("#gvClinic_udTransaction tr td:nth-child(1)").each(function () {
                    var cellText = $(this).text().toLowerCase();
                    if (cellText.indexOf(searchKey) >= 0) {
                        $(this).parent().show();
                    }
                    else {
                        $(this).parent().hide();
                    }
                });
            });
            /////////////////////////////////////////////////
            //////////// End Clinic_ud Tab //////////////////
            /////////////////////////////////////////////////
            /// Eng.Moustafa Ebrahem
            /// Eng.Moustafa20@Gmail.com
        }
        function ClearClinic_udtbl() {
            $('#btnClinic_udSave').attr('disabled', true);
            $("#gvClinic_ud .gvrow").removeClass("blue3");
            $('#tblClinic_udany').fClear();
        }
        function ClearClinic_udSrch() {
            $('#txtSrchDategvClinic_udTrans').val('');
        }
        function Msignalr() {
            // Call the Withdrawals method on the hub.
            serverHub.server.withdrawals();
        }
    </script>
</head>
<body class='<%= this.user!=null?this.user.theme:"theme-grey"%>'>
    <form id="form1" runat="server">
        <asp:ScriptManager ID="ScriptManager1" runat="server">
        </asp:ScriptManager>
        <asp:Button ID="btnDefault" runat="server" OnClientClick="return false;" CssClass="hide" />
        <uc1:ucFinancials runat="server" ID="ucFinancials" />
        <div id="content" class="container-fluid nav-fixed">
            <div id="main" style="margin-left: 0px;">
                <div class="container-fluid">
                    <div class="page-header">
                        <div class="pull-left">
                            <h2 meta:resourcekey="hWithdrawals" runat="server">Withdrawals</h2>
                        </div>
                        <div class="pull-right">
                            <ul class="stats">
                                <li class='grey'><i class="icon-calendar"></i>
                                    <div class="details">
                                        <span class="big">August 14, 2013</span> <span>Wednesday, 04:04</span>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="row-fluid">
                        <div class="span12">
                            <div class="box box-color">
                                <div class="box-title">
                                    <h3 meta:resourcekey="hWithdrawalsSett" runat="server">
                                        <i class="glyphicon-credit_card"></i>Withdrawals
                                    </h3>
                                    <ul class="tabs">
                                        <li class="active"><a href="#t1" data-toggle="tab" meta:resourcekey="aCS" runat="server">Clinic_ud Safe</a></li>
                                    </ul>
                                </div>
                                <div class="box-content nopadding">
                                    <div class="tab-content">
                                        <div id="t1" class="tab-pane active">
                                            <div class='form-horizontal form-column form-bordered'>
                                                <asp:UpdatePanel ID="upClinic_udanies" runat="server" UpdateMode="Conditional">
                                                    <ContentTemplate>
                                                        <div class="box box-bordered box-color">
                                                            <div class="box-title">
                                                                <h3 meta:resourcekey="hCSS" runat="server">
                                                                    <i class="glyphicon-briefcase"></i>Clinic_ud Safe</h3>
                                                            </div>
                                                            <div class="box-content nopadding">
                                                                <div class="span6">
                                                                    <br />
                                                                    <br />
                                                                    <div class="scroll scrollmini">
                                                                        <asp:GridView ID="gvClinic_ud" runat="server" CssClass="tblbordered" Width="100%" AutoGenerateColumns="False"
                                                                            EmptyDataText="No Results Found" meta:resourcekey="gvClinic_udResource1">
                                                                            <Columns>
                                                                                <asp:BoundField DataField="Clinic_ud_id" HeaderText="ID" meta:resourcekey="BoundFieldResource1">
                                                                                    <HeaderStyle CssClass="hide" />
                                                                                    <ItemStyle CssClass="hide" />
                                                                                </asp:BoundField>
                                                                                <asp:BoundField DataField="Clinic_ud_name" HeaderText="Safe Name" meta:resourcekey="BoundFieldResource2" />
                                                                                <asp:BoundField DataField="Clinic_ud_code" HeaderText="Code" meta:resourcekey="BoundFieldResource3">
                                                                                    <HeaderStyle CssClass="hide" />
                                                                                    <ItemStyle CssClass="hide" />
                                                                                </asp:BoundField>
                                                                                <asp:BoundField DataField="Clinic_ud_balance" HeaderText="Balance" meta:resourcekey="BoundFieldResource4" />
                                                                            </Columns>
                                                                            <HeaderStyle CssClass="gvgray" />
                                                                            <RowStyle CssClass="blue2 gvrow" />
                                                                            <SelectedRowStyle CssClass="blue3 gvrow" />
                                                                            <EmptyDataRowStyle CssClass="gvempty" />
                                                                        </asp:GridView>
                                                                    </div>
                                                                </div>
                                                                <div id="tblClinic_udany" class="span6">
                                                                    <div class="control-group">
                                                                        <label for="textfield" class="control-label" meta:resourcekey="lblActions" runat="server">
                                                                            Actions:</label>
                                                                        <div class="controls">
                                                                            <input type="button" id="btnClinic_udNew" value="New" class="btn btn-grey" style="width: 75px" meta:resourcekey="btnNew" runat="server" />
                                                                            <asp:Button ID="btnClinic_udSave" Text="Save" runat="server" CssClass="btn btn-blue"
                                                                                Width="75px" OnClick="btnClinic_udSave_Click" ValidationGroup="c" CommandArgument="save" meta:resourcekey="btnClinic_udSaveResource1" />
                                                                            <asp:Button ID="btnRefresh" runat="server" CssClass="hide" OnClick="btnRefresh_Click" ValidationGroup="w"/>
                                                                        </div>
                                                                    </div>
                                                                    <div class="control-group hidden">
                                                                        <label for="textfield" class="control-label" meta:resourcekey="lblCode" runat="server">
                                                                            Code:</label>
                                                                        <div class="controls">
                                                                            <input id="txtClinic_udCode" runat="server" type="text" placeholder="Clinic_ud Code" class="input-xlarge"
                                                                                disabled="disabled" autocomplete="off" />
                                                                            <asp:RequiredFieldValidator ID="rvtxtClinic_udCode" runat="server" ControlToValidate="txtClinic_udCode"
                                                                                Display="Dynamic" ErrorMessage="*Required" ForeColor="#CC0000" SetFocusOnError="True"
                                                                                ValidationGroup="c" meta:resourcekey="rvtxtClinic_udCodeResource1"></asp:RequiredFieldValidator>
                                                                            <input id="txtClinic_udId" runat="server" type="text" placeholder="Clinic_ud ID" class="hide"
                                                                                disabled="disabled" />
                                                                            <asp:RequiredFieldValidator ID="rvtxtClinic_udId" runat="server" ControlToValidate="txtClinic_udId"
                                                                                Display="Dynamic" ForeColor="#CC0000" SetFocusOnError="True"
                                                                                ValidationGroup="c" meta:resourcekey="rvtxtClinic_udIdResource1"></asp:RequiredFieldValidator>
                                                                        </div>
                                                                    </div>
                                                                    <div class="control-group">
                                                                        <label for="textfield" class="control-label" meta:resourcekey="lblBalance" runat="server">
                                                                            Balance:</label>
                                                                        <div class="controls">
                                                                            <input id="txtClinic_udBalance" runat="server" type="text" placeholder="Clinic_ud's Balance"
                                                                                class="input-xlarge" disabled="disabled" autocomplete="off" meta:resourcekey="txtClinic_udBalance" />
                                                                        </div>
                                                                    </div>
                                                                    <div class="control-group">
                                                                        <label for="textfield" class="control-label" meta:resourcekey="lblAmount" runat="server">
                                                                            Amount:</label>
                                                                        <div class="controls">
                                                                            <input id="txtClinic_udAmount" runat="server" type="text" placeholder="Amount withdrawn"
                                                                                maxlength="21" autocomplete="off" class="input-xlarge txtFocus" meta:resourcekey="txtAmount" />
                                                                            <asp:RequiredFieldValidator ID="rvtxtClinic_udAmount" runat="server" ControlToValidate="txtClinic_udAmount"
                                                                                Display="Dynamic" ErrorMessage="*Required" ForeColor="#CC0000" SetFocusOnError="True"
                                                                                ValidationGroup="c" meta:resourcekey="rvtxtClinic_udAmountResource1"></asp:RequiredFieldValidator>
                                                                            <asp:RegularExpressionValidator ID="retxtClinic_udAmount" runat="server" ControlToValidate="txtClinic_udAmount"
                                                                                ErrorMessage="*Error" Display="Dynamic" ForeColor="#CC0000" SetFocusOnError="True"
                                                                                ValidationExpression="^\d{0,18}([\.]\d{1,2})?$" ValidationGroup="c" meta:resourcekey="retxtClinic_udAmountResource1"></asp:RegularExpressionValidator>
                                                                            <asp:CompareValidator ID="cvretxtClinic_udAmount" runat="server" ControlToCompare="txtClinic_udBalance"
                                                                                ControlToValidate="txtClinic_udAmount" ErrorMessage="<br/>Amount withdrawn should be less than<br/>or equal to Clinic_ud's balance"
                                                                                Operator="LessThanEqual" SetFocusOnError="True" Type="Currency" ValidationGroup="c"
                                                                                Display="Dynamic" ForeColor="#CC0000" meta:resourcekey="cvretxtClinic_udAmountResource1"></asp:CompareValidator>
                                                                        </div>
                                                                    </div>
                                                                    <div class="control-group">
                                                                        <label for="textfield" class="control-label" meta:resourcekey="lblNote" runat="server">
                                                                            Note:</label>
                                                                        <div class="controls">
                                                                            <input id="txtClinic_udNote" runat="server" type="text" placeholder="Note" maxlength="50"
                                                                                autocomplete="off" class="input-xlarge" meta:resourcekey="txtNote" />
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="box box-color box-bordered">
                                                            <div class="box-title">
                                                                <h3 meta:resourcekey="hTransactions_ud" runat="server">
                                                                    <i class="icon-money"></i>Transactions_ud</h3>
                                                            </div>
                                                            <div class="box-content nopadding">
                                                                <div class="span12">
                                                                    <div class="div_search_box">
                                                                        <div class="input-append input-prepend">
                                                                            <span class="add-on">
                                                                                <li class="icon-search"></li>
                                                                            </span>
                                                                            <input id="txtSrchDategvClinic_udTrans" type="text" value="" class="input-large" placeholder="Search By Date..."
                                                                                autocomplete="off" meta:resourcekey="txtSrchDate" runat="server" />
                                                                        </div>
                                                                    </div>
                                                                    <div class="scroll scrollbig2">
                                                                        <asp:GridView ID="gvClinic_udTransaction" runat="server" CssClass="tblbordered" Width="100%" AutoGenerateColumns="False"
                                                                            EmptyDataText="No Results Found" meta:resourcekey="gvClinic_udTransactionResource1">
                                                                            <Columns>
                                                                                <asp:BoundField DataField="transact_date" HeaderText="Date" meta:resourcekey="BoundFieldResource5" />
                                                                                <asp:BoundField DataField="transact_amount" HeaderText="Amount" meta:resourcekey="BoundFieldResource6" />
                                                                                <asp:BoundField DataField="last_clc_balance" HeaderText="Last Cash" meta:resourcekey="BoundFieldResource7" />
                                                                                <asp:BoundField DataField="transact_note" HeaderText="Note" meta:resourcekey="BoundFieldResource8" />
                                                                                <asp:BoundField DataField="user_name" HeaderText="User" meta:resourcekey="BoundFieldResource9" />
                                                                            </Columns>
                                                                            <HeaderStyle CssClass="gvgray" />
                                                                            <RowStyle CssClass="blue2 gvrow2" />
                                                                            <SelectedRowStyle CssClass="blue3 gvrow2" />
                                                                            <EmptyDataRowStyle CssClass="gvempty" />
                                                                        </asp:GridView>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </ContentTemplate>
                                                </asp:UpdatePanel>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <br />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div id="modal-1" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
            aria-hidden="true">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
                    ×</button>
                <h3 id="myModalLabel" meta:resourcekey="myModalLabel" runat="server">Saving Confirmation</h3>
            </div>
            <div class="modal-body">
                <p meta:resourcekey="pSave" runat="server">
                    Are you sure that you want to save this operation ?
                </p>
                <p meta:resourcekey="pNote" runat="server">
                    <b>Note: There is no undo for this operation</b>
                </p>
            </div>
            <div class="modal-footer">
                <button class="btn" data-dismiss="modal" aria-hidden="true" meta:resourcekey="btnNo" runat="server">
                    No
                </button>
                <button id="btnConfirm" class="btn btn-primary" data-dismiss="modal" meta:resourcekey="btnYes" runat="server">
                    Yes
                </button>
            </div>
        </div>
        <asp:HiddenField ID="hfTheme" runat="server" ClientIDMode="Static" />
        <asp:Button ID="btnSaveTheme" runat="server" OnClick="btnSaveTheme_Click" CssClass="hide" />
        <div id="footer">
            <p id="P2" meta:resourcekey="pAboutus" runat="server">
                Umbrella v3.4 - © All Rights Reserved For APPLET Software <span class="font-grey-4">|</span><a href="AboutUs.aspx" target="_blank"> About Us </a>
            </p>
            <a href="#" class="gototop"><i class="icon-arrow-up"></i></a>
        </div>
    </form>
</body>
</html>
