//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Clinic
{
    public Clinic()
    {
        this.Transactions = new HashSet<Transaction>();
    }

    public int clinic_id { get; set; }
    public string clinic_name { get; set; }
    public string header_line1 { get; set; }
    public string header_line2 { get; set; }
    public string header_line3 { get; set; }
    public string header_line4 { get; set; }
    public string footer_line1 { get; set; }
    public string footer_line2 { get; set; }
    public string footer_line3 { get; set; }
    public string footer_line4 { get; set; }
    public string clinic_code { get; set; }
    public Nullable<decimal> clinic_balance { get; set; }
    public string clinic_name_ar { get; set; }

    public virtual ICollection<Transaction> Transactions { get; set; }
}

public partial class Company
{
    public Company()
    {
        this.Company_Pat_Det = new HashSet<Company_Pat_Det>();
        this.Pat_Visits = new HashSet<Pat_Visits>();
    }

    public int company_id { get; set; }
    public string company_name { get; set; }
    public string company_address { get; set; }
    public string company_phone { get; set; }
    public string company_mobile { get; set; }
    public string company_email { get; set; }
    public string company_website { get; set; }
    public string created_date { get; set; }
    public Nullable<int> created_by { get; set; }
    public string company_code { get; set; }
    public Nullable<decimal> company_balance { get; set; }
    public Nullable<bool> active { get; set; }

    public virtual User User { get; set; }
    public virtual ICollection<Company_Pat_Det> Company_Pat_Det { get; set; }
    public virtual ICollection<Pat_Visits> Pat_Visits { get; set; }
}

public partial class Company_Pat_Det
{
    public int company_pat_det_id { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> pat_id { get; set; }

    public virtual Company Company { get; set; }
    public virtual Patient Patient { get; set; }
}

public partial class Contract
{
    public Contract()
    {
        this.Pat_Visits = new HashSet<Pat_Visits>();
    }

    public int contract_id { get; set; }
    public Nullable<int> company_id { get; set; }
    public string contract_type { get; set; }
    public Nullable<int> contract_period { get; set; }
    public string contract_date_from { get; set; }
    public string contract_date_to { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public Nullable<int> contract_due_day { get; set; }
    public Nullable<int> warning { get; set; }
    public Nullable<bool> flag_visits { get; set; }
    public string created_date { get; set; }
    public Nullable<int> created_by { get; set; }

    public virtual ICollection<Pat_Visits> Pat_Visits { get; set; }
}

public partial class Day
{
    public Day()
    {
        this.Days_Det = new HashSet<Days_Det>();
    }

    public int day_id { get; set; }
    public string day_name { get; set; }
    public Nullable<bool> active { get; set; }
    public string day_name_ar { get; set; }

    public virtual ICollection<Days_Det> Days_Det { get; set; }
}

public partial class Days_Det
{
    public int day_det_id { get; set; }
    public Nullable<int> day_id { get; set; }
    public Nullable<System.TimeSpan> time_from { get; set; }
    public Nullable<System.TimeSpan> time_to { get; set; }

    public virtual Day Day { get; set; }
}

public partial class Diagnosis
{
    public Diagnosis()
    {
        this.Pat_Diagnosis = new HashSet<Pat_Diagnosis>();
    }

    public int diagnosis_id { get; set; }
    public string diagnosis_name { get; set; }
    public Nullable<bool> active { get; set; }

    public virtual ICollection<Pat_Diagnosis> Pat_Diagnosis { get; set; }
}

public partial class Dos
{
    public Dos()
    {
        this.Pat_Prescriptions_Det = new HashSet<Pat_Prescriptions_Det>();
    }

    public int dose_id { get; set; }
    public string dose_name { get; set; }
    public Nullable<bool> active { get; set; }

    public virtual ICollection<Pat_Prescriptions_Det> Pat_Prescriptions_Det { get; set; }
}

public partial class Employee
{
    public int emp_id { get; set; }
    public string emp_name { get; set; }
    public string emp_address { get; set; }
    public string emp_job { get; set; }
    public string emp_identity_no { get; set; }
    public string emp_mobile { get; set; }
    public string emp_phone { get; set; }
    public string emp_birthdate { get; set; }
    public string emp_hiredate { get; set; }
    public string emp_salary { get; set; }
    public Nullable<bool> active { get; set; }
}

public partial class Examination
{
    public Examination()
    {
        this.Examinations_Det = new HashSet<Examinations_Det>();
    }

    public int exam_id { get; set; }
    public string exam_name { get; set; }
    public Nullable<bool> active { get; set; }

    public virtual ICollection<Examinations_Det> Examinations_Det { get; set; }
}

public partial class Examinations_Det
{
    public Examinations_Det()
    {
        this.Pat_Visits = new HashSet<Pat_Visits>();
    }

    public int exam_det_id { get; set; }
    public Nullable<int> exam_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public Nullable<bool> active_det { get; set; }

    public virtual Examination Examination { get; set; }
    public virtual ICollection<Pat_Visits> Pat_Visits { get; set; }
}

public partial class Expens
{
    public int expense_id { get; set; }
    public string expense_name { get; set; }
    public string expense_code { get; set; }
    public Nullable<decimal> expense_balance { get; set; }
    public string expense_name_ar { get; set; }
}

public partial class Medicine
{
    public Medicine()
    {
        this.Pat_Prescriptions_Det = new HashSet<Pat_Prescriptions_Det>();
    }

    public int medicine_id { get; set; }
    public string medicine_name { get; set; }
    public Nullable<bool> active { get; set; }
    public Nullable<bool> common { get; set; }

    public virtual ICollection<Pat_Prescriptions_Det> Pat_Prescriptions_Det { get; set; }
}

public partial class Page
{
    public Page()
    {
        this.Users_Permissions = new HashSet<Users_Permissions>();
    }

    public int page_id { get; set; }
    public Nullable<int> section_id { get; set; }
    public string page_name_en { get; set; }
    public string page_name { get; set; }
    public Nullable<bool> IsView { get; set; }
    public Nullable<bool> IsSave { get; set; }
    public Nullable<bool> IsUpdate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<bool> Isprint { get; set; }
    public string page_name_ar { get; set; }

    public virtual Section Section { get; set; }
    public virtual ICollection<Users_Permissions> Users_Permissions { get; set; }
}

public partial class Pat_Chronic_Diseases
{
    public int pat_chronic_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_chronic_name { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_Complaints
{
    public int pat_complaint_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string pat_complaint_name { get; set; }
    public string pat_complaint_note { get; set; }

    public virtual Pat_Visits Pat_Visits { get; set; }
}

public partial class Pat_Diagnosis
{
    public int pat_diagnosis_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> diagnosis_id { get; set; }

    public virtual Diagnosis Diagnosis { get; set; }
    public virtual Pat_Visits Pat_Visits { get; set; }
}

public partial class Pat_Drugs
{
    public int pat_drug_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_drug_name { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_Family_History
{
    public int pat_family_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public Nullable<short> relationship { get; set; }
    public string pat_family_disease_name { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_Hospital_Admission
{
    public int pat_hospital_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_hospital_reason { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_Images
{
    public int pat_img_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_img_url { get; set; }
    public string pat_img_desc { get; set; }
    public string pat_img_date { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_Prescriptions
{
    public Pat_Prescriptions()
    {
        this.Pat_Prescriptions_Det = new HashSet<Pat_Prescriptions_Det>();
    }

    public int pat_prescription_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }

    public virtual ICollection<Pat_Prescriptions_Det> Pat_Prescriptions_Det { get; set; }
    public virtual Pat_Visits Pat_Visits { get; set; }
}

public partial class Pat_Prescriptions_Det
{
    public int pat_prescription_det_id { get; set; }
    public Nullable<int> pat_prescription_id { get; set; }
    public Nullable<int> medicine_id { get; set; }
    public Nullable<int> dose_id { get; set; }
    public string note { get; set; }

    public virtual Dos Dos { get; set; }
    public virtual Medicine Medicine { get; set; }
    public virtual Pat_Prescriptions Pat_Prescriptions { get; set; }
}

public partial class Pat_Requests
{
    public int pat_request_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }

    public virtual Pat_Visits Pat_Visits { get; set; }
}

public partial class Pat_Requests_Det
{
    public int pat_request_det_id { get; set; }
    public Nullable<int> pat_request_id { get; set; }
    public Nullable<int> test_id { get; set; }

    public virtual Test Test { get; set; }
}

public partial class Pat_Surgeries
{
    public int pat_surgery_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_surgery_name { get; set; }
    public string pat_surgery_date { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_transfusion
{
    public int pat_transfusion_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_transfusion_date { get; set; }

    public virtual Patient Patient { get; set; }
}

public partial class Pat_Visits
{
    public Pat_Visits()
    {
        this.Pat_Complaints = new HashSet<Pat_Complaints>();
        this.Pat_Diagnosis = new HashSet<Pat_Diagnosis>();
        this.Pat_Prescriptions = new HashSet<Pat_Prescriptions>();
        this.Pat_Requests = new HashSet<Pat_Requests>();
        this.Pat_Vital_Signs = new HashSet<Pat_Vital_Signs>();
        this.Transactions = new HashSet<Transaction>();
    }

    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_visit_date { get; set; }
    public Nullable<System.TimeSpan> pat_visit_time { get; set; }
    public Nullable<int> exam_det_id { get; set; }
    public Nullable<short> viacompany { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public Nullable<short> paid_status { get; set; }
    public Nullable<short> visit_status { get; set; }
    public Nullable<short> active { get; set; }
    public Nullable<int> user_id { get; set; }

    public virtual Company Company { get; set; }
    public virtual Contract Contract { get; set; }
    public virtual Examinations_Det Examinations_Det { get; set; }
    public virtual ICollection<Pat_Complaints> Pat_Complaints { get; set; }
    public virtual ICollection<Pat_Diagnosis> Pat_Diagnosis { get; set; }
    public virtual ICollection<Pat_Prescriptions> Pat_Prescriptions { get; set; }
    public virtual ICollection<Pat_Requests> Pat_Requests { get; set; }
    public virtual Patient Patient { get; set; }
    public virtual User User { get; set; }
    public virtual ICollection<Pat_Vital_Signs> Pat_Vital_Signs { get; set; }
    public virtual ICollection<Transaction> Transactions { get; set; }
}

public partial class Pat_Vital_Signs
{
    public int vital_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string vital_weight { get; set; }
    public string vital_height { get; set; }
    public string vital_temp { get; set; }
    public string vital_pulse { get; set; }
    public string vital_respiratory { get; set; }
    public string vital_blood { get; set; }
    public string vital_pupil { get; set; }
    public string vital_skin { get; set; }
    public string vital_notes { get; set; }

    public virtual Pat_Visits Pat_Visits { get; set; }
}

public partial class Patient
{
    public Patient()
    {
        this.Company_Pat_Det = new HashSet<Company_Pat_Det>();
        this.Pat_Chronic_Diseases = new HashSet<Pat_Chronic_Diseases>();
        this.Pat_Drugs = new HashSet<Pat_Drugs>();
        this.Pat_Family_History = new HashSet<Pat_Family_History>();
        this.Pat_Hospital_Admission = new HashSet<Pat_Hospital_Admission>();
        this.Pat_Images = new HashSet<Pat_Images>();
        this.Pat_Surgeries = new HashSet<Pat_Surgeries>();
        this.Pat_transfusion = new HashSet<Pat_transfusion>();
        this.Pat_Visits = new HashSet<Pat_Visits>();
    }

    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_birthdate { get; set; }
    public string pat_address { get; set; }
    public string pat_gender { get; set; }
    public string pat_mobile { get; set; }
    public string pat_phone { get; set; }
    public string pat_job { get; set; }
    public Nullable<int> marital_id { get; set; }
    public Nullable<int> blood_id { get; set; }
    public Nullable<bool> pat_smoker { get; set; }
    public Nullable<bool> pat_dm { get; set; }
    public Nullable<bool> pat_htn { get; set; }
    public string created_date { get; set; }
    public Nullable<int> created_by { get; set; }
    public string modified_date { get; set; }
    public Nullable<int> modified_by { get; set; }
    public string pat_code { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public Nullable<bool> active { get; set; }

    public virtual ICollection<Company_Pat_Det> Company_Pat_Det { get; set; }
    public virtual ICollection<Pat_Chronic_Diseases> Pat_Chronic_Diseases { get; set; }
    public virtual ICollection<Pat_Drugs> Pat_Drugs { get; set; }
    public virtual ICollection<Pat_Family_History> Pat_Family_History { get; set; }
    public virtual ICollection<Pat_Hospital_Admission> Pat_Hospital_Admission { get; set; }
    public virtual ICollection<Pat_Images> Pat_Images { get; set; }
    public virtual ICollection<Pat_Surgeries> Pat_Surgeries { get; set; }
    public virtual ICollection<Pat_transfusion> Pat_transfusion { get; set; }
    public virtual ICollection<Pat_Visits> Pat_Visits { get; set; }
    public virtual User User { get; set; }
    public virtual User User1 { get; set; }
}

public partial class Section
{
    public Section()
    {
        this.Pages = new HashSet<Page>();
    }

    public int section_id { get; set; }
    public string section_name { get; set; }
    public string section_name_ar { get; set; }

    public virtual ICollection<Page> Pages { get; set; }
}

public partial class sysdiagram
{
    public string name { get; set; }
    public int principal_id { get; set; }
    public int diagram_id { get; set; }
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class Test
{
    public Test()
    {
        this.Pat_Requests_Det = new HashSet<Pat_Requests_Det>();
    }

    public int test_id { get; set; }
    public string test_name { get; set; }
    public string test_type { get; set; }
    public Nullable<bool> active { get; set; }

    public virtual ICollection<Pat_Requests_Det> Pat_Requests_Det { get; set; }
}

public partial class Transaction
{
    public int transact_id { get; set; }
    public Nullable<System.DateTime> transact_date { get; set; }
    public Nullable<int> account_id { get; set; }
    public string account_code { get; set; }
    public Nullable<short> transact_desc { get; set; }
    public Nullable<short> transact_type { get; set; }
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<decimal> last_acc_balance { get; set; }
    public Nullable<decimal> last_clc_balance { get; set; }
    public Nullable<int> clinic_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public string transact_note { get; set; }

    public virtual Clinic Clinic { get; set; }
    public virtual Pat_Visits Pat_Visits { get; set; }
    public virtual User User { get; set; }
}

public partial class User
{
    public User()
    {
        this.Companies = new HashSet<Company>();
        this.Pat_Visits = new HashSet<Pat_Visits>();
        this.Patients = new HashSet<Patient>();
        this.Patients1 = new HashSet<Patient>();
        this.Transactions = new HashSet<Transaction>();
        this.Users_Permissions = new HashSet<Users_Permissions>();
    }

    public int user_id { get; set; }
    public string user_name { get; set; }
    public byte[] user_password { get; set; }
    public string user_email { get; set; }
    public Nullable<bool> admin { get; set; }
    public Nullable<bool> active { get; set; }
    public Nullable<bool> sounds { get; set; }
    public string theme { get; set; }

    public virtual ICollection<Company> Companies { get; set; }
    public virtual ICollection<Pat_Visits> Pat_Visits { get; set; }
    public virtual ICollection<Patient> Patients { get; set; }
    public virtual ICollection<Patient> Patients1 { get; set; }
    public virtual ICollection<Transaction> Transactions { get; set; }
    public virtual ICollection<Users_Permissions> Users_Permissions { get; set; }
}

public partial class Users_Permissions
{
    public int user_perm_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> page_id { get; set; }
    public Nullable<bool> can_view { get; set; }
    public Nullable<bool> can_save { get; set; }
    public Nullable<bool> can_update { get; set; }
    public Nullable<bool> can_delete { get; set; }
    public Nullable<bool> can_print { get; set; }

    public virtual Page Page { get; set; }
    public virtual User User { get; set; }
}

public partial class fn_get_dates_Result
{
    public string the_date { get; set; }
}

public partial class Procedure1_Result
{
    public Nullable<int> Column1 { get; set; }
    public Nullable<int> Column2 { get; set; }
}

public partial class sp_clinic_slc_by_id_Result
{
    public int clinic_id { get; set; }
    public string clinic_name { get; set; }
    public string header_line1 { get; set; }
    public string header_line2 { get; set; }
    public string header_line3 { get; set; }
    public string header_line4 { get; set; }
    public string footer_line1 { get; set; }
    public string footer_line2 { get; set; }
    public string footer_line3 { get; set; }
}

public partial class sp_clinic_slc_Result
{
    public int clinic_id { get; set; }
    public string clinic_name { get; set; }
    public string clinic_code { get; set; }
    public Nullable<decimal> clinic_balance { get; set; }
}

public partial class sp_companies_slc_all_Result
{
    public int company_id { get; set; }
    public string company_name { get; set; }
    public string company_address { get; set; }
    public string company_phone { get; set; }
    public string company_mobile { get; set; }
    public string company_email { get; set; }
    public string company_website { get; set; }
    public string created_date { get; set; }
    public string company_code { get; set; }
    public Nullable<decimal> company_balance { get; set; }
    public int user_id { get; set; }
    public string created_by { get; set; }
    public string active { get; set; }
    public string status { get; set; }
}

public partial class sp_companies_slc_Result
{
    public int company_id { get; set; }
    public string company_name { get; set; }
}

public partial class sp_company_pat_det_slc_all_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
}

public partial class sp_company_pat_det_slc_Result
{
    public int company_pat_det_id { get; set; }
    public int pat_id { get; set; }
    public string pat_name { get; set; }
}

public partial class sp_contratcs_slc_all_Result
{
    public int contract_id { get; set; }
    public Nullable<int> company_id { get; set; }
    public string contract_type { get; set; }
    public Nullable<int> contract_period { get; set; }
    public string contract_date_from { get; set; }
    public string contract_date_to { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public Nullable<int> contract_due_day { get; set; }
    public Nullable<int> warning { get; set; }
    public Nullable<bool> flag_visits { get; set; }
    public string created_date { get; set; }
    public string company_name { get; set; }
    public int user_id { get; set; }
    public string user_name { get; set; }
}

public partial class sp_contratcs_slc_valid_Result
{
    public int contract_id { get; set; }
    public Nullable<int> company_id { get; set; }
    public string contract_type { get; set; }
    public Nullable<int> contract_period { get; set; }
    public string contract_date_from { get; set; }
    public string contract_date_to { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public Nullable<int> contract_due_day { get; set; }
    public Nullable<int> warning { get; set; }
    public Nullable<bool> flag_visits { get; set; }
    public string created_date { get; set; }
    public string company_name { get; set; }
}

public partial class sp_days_det_slc_Result
{
    public int day_det_id { get; set; }
    public Nullable<int> day_id { get; set; }
    public string time_from { get; set; }
    public string time_to { get; set; }
}

public partial class sp_days_doctor_slc_Result
{
    public int day_id { get; set; }
    public string day_name { get; set; }
    public int day_det_id { get; set; }
    public string time_from { get; set; }
    public string time_to { get; set; }
}

public partial class sp_days_slc_all_Result
{
    public int day_id { get; set; }
    public string day_name { get; set; }
    public string day_name_ar { get; set; }
    public string active { get; set; }
}

public partial class sp_diagnosis_slc_all_Result
{
    public int diagnosis_id { get; set; }
    public string diagnosis_name { get; set; }
    public string active { get; set; }
    public string status { get; set; }
}

public partial class sp_doses_slc_all_Result
{
    public int dose_id { get; set; }
    public string dose_name { get; set; }
    public string active { get; set; }
    public string status { get; set; }
}

public partial class sp_employee_slc_all_Result
{
    public int emp_id { get; set; }
    public string emp_name { get; set; }
    public string emp_address { get; set; }
    public string emp_job { get; set; }
    public string emp_identity_no { get; set; }
    public string emp_mobile { get; set; }
    public string emp_phone { get; set; }
    public string emp_birthdate { get; set; }
    public string emp_hiredate { get; set; }
    public string emp_salary { get; set; }
    public string active { get; set; }
    public string status { get; set; }
}

public partial class sp_employee_slc_id_Result
{
    public int emp_id { get; set; }
    public string emp_name { get; set; }
    public string emp_address { get; set; }
    public string emp_job { get; set; }
    public string emp_identity_no { get; set; }
    public string emp_mobile { get; set; }
    public string emp_phone { get; set; }
    public string emp_birthdate { get; set; }
    public string emp_hiredate { get; set; }
    public string emp_salary { get; set; }
    public Nullable<bool> active { get; set; }
}

public partial class sp_examinations_slc_all_Result
{
    public int exam_id { get; set; }
    public string exam_name { get; set; }
    public string active { get; set; }
    public string status { get; set; }
    public int exam_det_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public Nullable<bool> active_det { get; set; }
    public string exam_full { get; set; }
}

public partial class sp_expenses_slc_all_Result
{
    public int expense_id { get; set; }
    public string expense_name { get; set; }
    public string expense_code { get; set; }
    public Nullable<decimal> expense_balance { get; set; }
}

public partial class sp_helpdiagramdefinition_Result
{
    public Nullable<int> version { get; set; }
    public byte[] definition { get; set; }
}

public partial class sp_helpdiagrams_Result
{
    public string Database { get; set; }
    public string Name { get; set; }
    public int ID { get; set; }
    public string Owner { get; set; }
    public int OwnerID { get; set; }
}

public partial class sp_medicines_search_Result
{
    public int medicine_id { get; set; }
    public string medicine_name { get; set; }
    public string active { get; set; }
    public string status { get; set; }
    public string common { get; set; }
}

public partial class sp_medicines_slc_all_Result
{
    public int medicine_id { get; set; }
    public string medicine_name { get; set; }
    public string active { get; set; }
    public string status { get; set; }
    public string common { get; set; }
}

public partial class sp_pat_chronic_slc_all_Result
{
    public int pat_chronic_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_chronic_name { get; set; }
}

public partial class sp_pat_complaints_slc_Result
{
    public int pat_complaint_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string pat_complaint_name { get; set; }
    public string pat_complaint_note { get; set; }
}

public partial class sp_pat_diagnosis_slc_all_Result
{
    public int pat_diagnosis_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> diagnosis_id { get; set; }
    public string diagnosis_name { get; set; }
}

public partial class sp_pat_drugs_slc_all_Result
{
    public int pat_drug_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_drug_name { get; set; }
}

public partial class sp_pat_family_slc_all_Result
{
    public int pat_family_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public Nullable<short> relationship { get; set; }
    public string rel_name { get; set; }
    public string pat_family_disease_name { get; set; }
}

public partial class sp_pat_family_slc_name_Result
{
    public int pat_family_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string relationship { get; set; }
    public string pat_family_disease_name { get; set; }
}

public partial class sp_pat_hospital_slc_all_Result
{
    public int pat_hospital_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_hospital_reason { get; set; }
}

public partial class sp_pat_images_slc_all_Result
{
    public int pat_img_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_img_url { get; set; }
    public string pat_img_desc { get; set; }
    public string pat_img_date { get; set; }
}

public partial class sp_pat_images_slc_id_Result
{
    public int pat_img_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_img_url { get; set; }
    public string pat_img_desc { get; set; }
    public string pat_img_date { get; set; }
}

public partial class sp_pat_requests_slc_Result
{
    public int pat_request_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public int pat_request_det_id { get; set; }
    public Nullable<int> pat_request_id1 { get; set; }
    public Nullable<int> test_id { get; set; }
    public string test_name { get; set; }
    public string test_type { get; set; }
}

public partial class sp_pat_surgery_slc_all_Result
{
    public int pat_surgery_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_surgery_name { get; set; }
    public string pat_surgery_date { get; set; }
}

public partial class sp_pat_transfusion_slc_all_Result
{
    public int pat_transfusion_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_transfusion_date { get; set; }
}

public partial class sp_pat_visits_slc_clc_Result
{
    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_visit_date { get; set; }
    public string pat_visit_time { get; set; }
    public string paid_status { get; set; }
    public string visit_status { get; set; }
    public string viacompany { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<int> exam_det_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public int user_id { get; set; }
    public string user_name { get; set; }
    public Nullable<decimal> transact_amount { get; set; }
}

public partial class sp_pat_visits_slc_current_Result
{
    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public string pat_visit_date { get; set; }
    public string pat_visit_time { get; set; }
    public string paid_status { get; set; }
    public string visit_status { get; set; }
    public string viacompany { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<int> exam_det_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public decimal transact_amount { get; set; }
    public int user_id { get; set; }
    public string user_name { get; set; }
}

public partial class sp_pat_visits_slc_new_Result
{
    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_visit_date { get; set; }
    public string pat_visit_time { get; set; }
    public string paid_status { get; set; }
    public string visit_status { get; set; }
    public string viacompany { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<int> exam_det_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public decimal transact_amount { get; set; }
    public int user_id { get; set; }
    public string user_name { get; set; }
}

public partial class sp_pat_visits_slc_wl_clc_Result
{
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
}

public partial class sp_pat_visits_slc_wl_Result
{
    public Nullable<long> rnk { get; set; }
    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_visit_date { get; set; }
    public string pat_visit_time { get; set; }
    public string paid_status { get; set; }
    public string visit_status { get; set; }
    public string exam_name { get; set; }
    public int user_id { get; set; }
    public string user_name { get; set; }
}

public partial class sp_pat_vital_signs_slc_Result
{
    public int vital_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string vital_weight { get; set; }
    public string vital_height { get; set; }
    public string vital_temp { get; set; }
    public string vital_pulse { get; set; }
    public string vital_respiratory { get; set; }
    public string vital_blood { get; set; }
    public string vital_pupil { get; set; }
    public string vital_skin { get; set; }
    public string vital_notes { get; set; }
}

public partial class sp_patient_search_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_birthdate { get; set; }
    public string pat_address { get; set; }
    public string pat_gender { get; set; }
    public string pat_mobile { get; set; }
    public string pat_phone { get; set; }
    public string pat_job { get; set; }
    public Nullable<int> marital_id { get; set; }
    public Nullable<int> blood_id { get; set; }
    public Nullable<bool> pat_smoker { get; set; }
    public Nullable<bool> pat_dm { get; set; }
    public Nullable<bool> pat_htn { get; set; }
    public string created_date { get; set; }
    public Nullable<int> created_by { get; set; }
    public string modified_date { get; set; }
    public Nullable<int> modified_by { get; set; }
    public string pat_code { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public Nullable<bool> active { get; set; }
}

public partial class sp_patients_search_comp_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_birthdate { get; set; }
    public string pat_address { get; set; }
    public string pat_gender { get; set; }
    public string pat_mobile { get; set; }
    public string pat_phone { get; set; }
    public string pat_job { get; set; }
    public Nullable<int> marital_id { get; set; }
    public Nullable<int> blood_id { get; set; }
    public int pat_smoker { get; set; }
    public int pat_dm { get; set; }
    public int pat_htn { get; set; }
    public string created_date { get; set; }
    public string created_by { get; set; }
    public string modified_date { get; set; }
    public string modified_by { get; set; }
    public string pat_code { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public int active { get; set; }
}

public partial class sp_patients_search_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_birthdate { get; set; }
    public string pat_address { get; set; }
    public string pat_gender { get; set; }
    public string pat_mobile { get; set; }
    public string pat_phone { get; set; }
    public string pat_job { get; set; }
    public Nullable<int> marital_id { get; set; }
    public Nullable<int> blood_id { get; set; }
    public int pat_smoker { get; set; }
    public int pat_dm { get; set; }
    public int pat_htn { get; set; }
    public string created_date { get; set; }
    public string created_by { get; set; }
    public string modified_date { get; set; }
    public string modified_by { get; set; }
    public string pat_code { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public int active { get; set; }
    public string gen { get; set; }
    public string status { get; set; }
}

public partial class sp_patients_slc_all_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_birthdate { get; set; }
    public string pat_address { get; set; }
    public string pat_gender { get; set; }
    public string pat_mobile { get; set; }
    public string pat_phone { get; set; }
    public string pat_job { get; set; }
    public Nullable<int> marital_id { get; set; }
    public Nullable<int> blood_id { get; set; }
    public int pat_smoker { get; set; }
    public int pat_dm { get; set; }
    public int pat_htn { get; set; }
    public string created_date { get; set; }
    public string created_by { get; set; }
    public string modified_date { get; set; }
    public string modified_by { get; set; }
    public string pat_code { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public int active { get; set; }
    public string gen { get; set; }
    public string status { get; set; }
}

public partial class sp_patients_slc_id_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_age { get; set; }
    public string pat_gender { get; set; }
    public Nullable<int> marital_id { get; set; }
    public Nullable<int> blood_id { get; set; }
    public int pat_smoker { get; set; }
    public int pat_dm { get; set; }
    public int pat_htn { get; set; }
}

public partial class sp_prescription_visit_slc_Result
{
    public int pat_prescription_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public int pat_prescription_det_id { get; set; }
    public Nullable<int> medicine_id { get; set; }
    public string medicine_name { get; set; }
    public Nullable<int> dose_id { get; set; }
    public string dose_name { get; set; }
    public string note { get; set; }
}

public partial class sp_rpt_basic_info_Result
{
    public string header_line1 { get; set; }
    public string header_line2 { get; set; }
    public string header_line3 { get; set; }
    public string header_line4 { get; set; }
    public string footer_line1 { get; set; }
    public string footer_line2 { get; set; }
    public string footer_line3 { get; set; }
}

public partial class sp_rpt_complaint_diagnosis_slc_Result
{
    public int pat_diagnosis_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> diagnosis_id { get; set; }
    public string diagnosis_name { get; set; }
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_visit_date { get; set; }
}

public partial class sp_rpt_complaint_slc_Result
{
    public int pat_complaint_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string pat_complaint_name { get; set; }
    public string pat_complaint_note { get; set; }
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_visit_date { get; set; }
}

public partial class sp_rpt_daily_det_encash_comp_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string transact_note { get; set; }
    public string user_name { get; set; }
    public string company_name { get; set; }
    public string company_code { get; set; }
}

public partial class sp_rpt_daily_det_encash_pat_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string transact_note { get; set; }
    public string user_name { get; set; }
    public string pat_name { get; set; }
    public string pat_code { get; set; }
}

public partial class sp_rpt_daily_det_pay_comp_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string transact_note { get; set; }
    public string user_name { get; set; }
    public string company_name { get; set; }
    public string company_code { get; set; }
}

public partial class sp_rpt_daily_det_pay_exp_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string transact_note { get; set; }
    public string user_name { get; set; }
    public string expense_name { get; set; }
    public string expense_code { get; set; }
}

public partial class sp_rpt_daily_det_pay_pat_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string transact_note { get; set; }
    public string user_name { get; set; }
    public string pat_name { get; set; }
    public string pat_code { get; set; }
}

public partial class sp_rpt_daily_det_ret_visits_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string user_name { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string viacompany { get; set; }
    public string pat_name { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public string contract_discount { get; set; }
}

public partial class sp_rpt_daily_det_visits_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string user_name { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string viacompany { get; set; }
    public string pat_name { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public string contract_discount { get; set; }
}

public partial class sp_rpt_daily_det_with_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string transact_note { get; set; }
    public string user_name { get; set; }
    public string clinic_name { get; set; }
    public string clinic_code { get; set; }
}

public partial class sp_rpt_pat_images_slc_Result
{
    public int pat_img_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_img_url { get; set; }
    public string pat_img_desc { get; set; }
    public string pat_img_date { get; set; }
    public string url { get; set; }
}

public partial class sp_rpt_patient_info_Result
{
    public int pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_age { get; set; }
    public string pat_gender { get; set; }
    public string marital_id { get; set; }
    public string blood_id { get; set; }
    public string pat_smoker { get; set; }
    public string pat_dm { get; set; }
    public string pat_htn { get; set; }
}

public partial class sp_rpt_prescription_slc_Result
{
    public int pat_prescription_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string medicine_name { get; set; }
    public string dose_name { get; set; }
    public string note { get; set; }
    public string pat_visit_date { get; set; }
    public int pat_id { get; set; }
    public string pat_name { get; set; }
}

public partial class sp_rpt_request_slc_Result
{
    public int pat_request_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public int pat_request_det_id { get; set; }
    public Nullable<int> pat_request_id1 { get; set; }
    public Nullable<int> test_id { get; set; }
    public string test_name { get; set; }
    public string test_type { get; set; }
    public string pat_visit_date { get; set; }
    public int pat_id { get; set; }
    public string pat_name { get; set; }
}

public partial class sp_rpt_visit_slc_Result
{
    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
    public string pat_visit_date { get; set; }
    public string pat_visit_time { get; set; }
    public string paid_status { get; set; }
    public string visit_status { get; set; }
    public string viacompany { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<int> exam_det_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public string contract_discount { get; set; }
    public string reserved_by { get; set; }
    public Nullable<int> transact_id { get; set; }
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.DateTime> transact_date { get; set; }
    public string paid_by { get; set; }
}

public partial class sp_rpt_vital_signs_slc_Result
{
    public int vital_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string vital_weight { get; set; }
    public string vital_height { get; set; }
    public string vital_temp { get; set; }
    public string vital_pulse { get; set; }
    public string vital_respiratory { get; set; }
    public string vital_blood { get; set; }
    public string vital_notes { get; set; }
    public string vital_pupil { get; set; }
    public string vital_skin { get; set; }
    public string pat_visit_date { get; set; }
    public int pat_id { get; set; }
    public string pat_name { get; set; }
}

public partial class sp_select_Pat_visits_Result
{
    public int pat_visit_id { get; set; }
    public Nullable<int> pat_id { get; set; }
    public string pat_name { get; set; }
    public Nullable<decimal> pat_balance { get; set; }
    public string pat_visit_date { get; set; }
    public string pat_visit_time { get; set; }
    public string paid_status { get; set; }
    public string visit_status { get; set; }
    public string viacompany { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<int> exam_det_id { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public Nullable<int> contract_discount { get; set; }
    public decimal transact_amount { get; set; }
    public int user_id { get; set; }
    public string user_name { get; set; }
}

public partial class sp_tests_slc_all_Result
{
    public int test_id { get; set; }
    public string test_name { get; set; }
    public string active { get; set; }
    public string status { get; set; }
}

public partial class sp_transactions_daily_det_Result
{
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<System.TimeSpan> time { get; set; }
    public string user_name { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public string viacompany { get; set; }
    public string pat_name { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> contract_id { get; set; }
    public string company_name { get; set; }
    public string exam_name { get; set; }
    public string exam_full { get; set; }
    public Nullable<decimal> exam_cost { get; set; }
    public string contract_discount { get; set; }
}

public partial class sp_transactions_daily_Result
{
    public Nullable<decimal> start_balance { get; set; }
    public Nullable<decimal> income { get; set; }
    public Nullable<decimal> outcome { get; set; }
    public Nullable<decimal> withdrawals { get; set; }
    public Nullable<decimal> balance { get; set; }
}

public partial class sp_transactions_slc_encashment_Result
{
    public int transact_id { get; set; }
    public Nullable<System.DateTime> transact_date { get; set; }
    public Nullable<int> account_id { get; set; }
    public string account_code { get; set; }
    public Nullable<short> transact_desc { get; set; }
    public Nullable<short> transact_type { get; set; }
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<decimal> last_acc_balance { get; set; }
    public Nullable<decimal> last_clc_balance { get; set; }
    public Nullable<int> clinic_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public string transact_note { get; set; }
    public int user_id1 { get; set; }
    public string user_name { get; set; }
    public byte[] user_password { get; set; }
    public string user_email { get; set; }
    public Nullable<bool> admin { get; set; }
    public Nullable<bool> active { get; set; }
    public Nullable<bool> sounds { get; set; }
    public string theme { get; set; }
    public string user_name1 { get; set; }
}

public partial class sp_transactions_slc_payment_Result
{
    public int transact_id { get; set; }
    public Nullable<System.DateTime> transact_date { get; set; }
    public Nullable<int> account_id { get; set; }
    public string account_code { get; set; }
    public Nullable<short> transact_desc { get; set; }
    public Nullable<short> transact_type { get; set; }
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<decimal> last_acc_balance { get; set; }
    public Nullable<decimal> last_clc_balance { get; set; }
    public Nullable<int> clinic_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public string transact_note { get; set; }
    public int user_id1 { get; set; }
    public string user_name { get; set; }
    public byte[] user_password { get; set; }
    public string user_email { get; set; }
    public Nullable<bool> admin { get; set; }
    public Nullable<bool> active { get; set; }
    public Nullable<bool> sounds { get; set; }
    public string theme { get; set; }
    public string user_name1 { get; set; }
}

public partial class sp_transactions_slc_withdrawals_Result
{
    public int transact_id { get; set; }
    public Nullable<System.DateTime> transact_date { get; set; }
    public Nullable<int> account_id { get; set; }
    public string account_code { get; set; }
    public Nullable<short> transact_desc { get; set; }
    public Nullable<short> transact_type { get; set; }
    public Nullable<decimal> transact_amount { get; set; }
    public Nullable<decimal> last_acc_balance { get; set; }
    public Nullable<decimal> last_clc_balance { get; set; }
    public Nullable<int> clinic_id { get; set; }
    public Nullable<int> pat_visit_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public string transact_note { get; set; }
    public int user_id1 { get; set; }
    public string user_name { get; set; }
    public byte[] user_password { get; set; }
    public string user_email { get; set; }
    public Nullable<bool> admin { get; set; }
    public Nullable<bool> active { get; set; }
    public Nullable<bool> sounds { get; set; }
    public string theme { get; set; }
    public string user_name1 { get; set; }
}

public partial class sp_users_perm_by_sec_Result
{
    public Nullable<int> section_id { get; set; }
    public string page_name_en { get; set; }
    public int user_perm_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> page_id { get; set; }
    public Nullable<bool> can_view { get; set; }
    public Nullable<bool> can_save { get; set; }
    public Nullable<bool> can_update { get; set; }
    public Nullable<bool> can_delete { get; set; }
    public Nullable<bool> can_print { get; set; }
}

public partial class sp_users_perm_pages_lang_Result
{
    public int page_id { get; set; }
    public Nullable<int> section_id { get; set; }
    public string page_name_en { get; set; }
    public string page_name { get; set; }
    public Nullable<bool> IsView { get; set; }
    public Nullable<bool> IsSave { get; set; }
    public Nullable<bool> IsUpdate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<bool> Isprint { get; set; }
}

public partial class sp_users_perm_pages_Result
{
    public int page_id { get; set; }
    public Nullable<int> section_id { get; set; }
    public string page_name_en { get; set; }
    public string page_name { get; set; }
    public Nullable<bool> IsView { get; set; }
    public Nullable<bool> IsSave { get; set; }
    public Nullable<bool> IsUpdate { get; set; }
    public Nullable<bool> IsDelete { get; set; }
    public Nullable<bool> Isprint { get; set; }
    public string page_name_ar { get; set; }
}

public partial class sp_users_perm_pages_sec_Result
{
    public Nullable<int> section_id { get; set; }
    public string page_name_en { get; set; }
    public int user_perm_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> page_id { get; set; }
    public Nullable<bool> can_view { get; set; }
    public Nullable<bool> can_save { get; set; }
    public Nullable<bool> can_update { get; set; }
    public Nullable<bool> can_delete { get; set; }
    public Nullable<bool> can_print { get; set; }
}

public partial class sp_users_perm_sections_Result
{
    public int section_id { get; set; }
    public string section_name { get; set; }
}

public partial class sp_users_perm_slc_all_Result
{
    public int user_perm_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> page_id { get; set; }
    public Nullable<bool> can_view { get; set; }
    public Nullable<bool> can_save { get; set; }
    public Nullable<bool> can_update { get; set; }
    public Nullable<bool> can_delete { get; set; }
    public Nullable<bool> can_print { get; set; }
    public Nullable<int> section_id { get; set; }
}

public partial class sp_users_perm_slc_page_Result
{
    public int user_perm_id { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> page_id { get; set; }
    public Nullable<bool> can_view { get; set; }
    public Nullable<bool> can_save { get; set; }
    public Nullable<bool> can_update { get; set; }
    public Nullable<bool> can_delete { get; set; }
    public Nullable<bool> can_print { get; set; }
    public Nullable<int> section_id { get; set; }
    public string page_name_en { get; set; }
}

public partial class sp_users_slc_all_Result
{
    public int user_id { get; set; }
    public string user_name { get; set; }
    public string user_password { get; set; }
    public string user_email { get; set; }
    public string admin { get; set; }
    public string isadmin { get; set; }
    public string active { get; set; }
    public string status { get; set; }
}

public partial class sp_users_slc_by_email_Result
{
    public string user_name { get; set; }
    public string user_password { get; set; }
}

public partial class sp_users_slc_id_Result
{
    public int user_id { get; set; }
    public string user_name { get; set; }
    public byte[] user_password { get; set; }
    public string user_email { get; set; }
    public Nullable<bool> admin { get; set; }
    public Nullable<bool> active { get; set; }
    public Nullable<bool> sounds { get; set; }
    public string theme { get; set; }
}

public partial class sp_users_slc_username_Result
{
    public int user_id { get; set; }
    public string user_name { get; set; }
    public string user_email { get; set; }
    public string admin { get; set; }
    public string active { get; set; }
    public string sounds { get; set; }
    public string msounds { get; set; }
    public string theme { get; set; }
}
